### ISSUE TITLE
GetPlayerWeaponState

### ISSUE THREAD

**Issue by Disinterpreter** [qaisjp/mta-amx#19]
**Function name**
GetPlayerWeaponState(playerid)

**Describe the function**
Check the state of a player's weapon.

**Equivalent in MTA**
 [GetPedTotalAmmo](https://wiki.multitheftauto.com/wiki/GetPedTotalAmmo)
[isPedReloadingWeapon](https://wiki.multitheftauto.com/wiki/IsPedReloadingWeapon) from https://github.com/multitheftauto/amx/issues/19#issuecomment-643776335

**Additional information**
https://wiki.sa-mp.com/wiki/GetPlayerWeaponState
https://wiki.sa-mp.com/wiki/Weaponstates

**Comment by qaisjp** [comment]
and [isPedReloadingWeapon](https://wiki.multitheftauto.com/wiki/IsPedReloadingWeapon)
