### ISSUE TITLE
GetVehicleParamsSirenState

### ISSUE THREAD

**Issue by Disinterpreter** [qaisjp/mta-amx#35]
**Function name**
GetVehicleParamsSirenState(vehicleid)

**Describe the function**
Returns a vehicle's siren state (on/off).

**Equivalent in MTA**
https://wiki.multitheftauto.com/wiki/GetVehicleSirensOn

**Additional information**
https://wiki.sa-mp.com/wroot/index.php?title=GetVehicleParamsSirenState

**Comment by colistro123** [comment]
Added by Disinterpreter in commit https://github.com/multitheftauto/amx/commit/03c88c720b674b9e4c2da7928d3464712e80f7bc
