### ISSUE TITLE
Refactor sycalls.lua

### ISSUE THREAD

**Issue by Disinterpreter** [qaisjp/mta-amx#5]
Earlier we take this library for our idea. And we refactored a syscalls file for the logical view.
Out can check it out ![here](https://github.com/Disinterpreter/pmta-wrapper/tree/master/%5Bgamemodes%5D/%5Bamx%5D/pmta-wrapper/server)

I suggest make it same.
Split a syscalls.lua file to ![same](https://github.com/Disinterpreter/pmta-wrapper/tree/master/%5Bgamemodes%5D/%5Bamx%5D/pmta-wrapper/server/function) files.

**Comment by qaisjp** [comment]
Yes, I agree we should split `syscalls.lua` into separate files!

**Comment by Disinterpreter** [comment]
Fixed in https://github.com/multitheftauto/amx/pull/62
