### ISSUE TITLE
License

### ISSUE THREAD

**Issue by theSpool** [qaisjp/mta-amx#8]
I noticed this repo and mtasa-resources don't have a license. I was looking to add a file from AMXModX, which is GPL 3.0. (namely a slightly old version of format.cpp, which is used by SA-MP to format strings in custom versions of the `printf` and `format`. The natives provided by `amx_ConsoleInit` are not actually used). mtasa-blue is GPL 3.0, so my assumption is that everything here also is GPL 3.0, but I'm not 100% if that's the case. It would be ideal to specify the license ASAP to avoid any problems if we want to use external stuff.

On the other hand, AMX/Pawn uses the "zLib/libpng" license which is very permissive (and therefore GPL compatible), so no problems on that regard.

As a side note, I realized SA-MP violates GPL because it doesn't publicly provide the source of this file!

**Comment by qaisjp** [comment]
Heh, yes, this is a little complicated.

Some more context:

- https://github.com/multitheftauto/mtasa-resources is missing a license
- but I believe that repo is licensed MIT, because the old Google Code repository says it is licensed MIT: https://code.google.com/archive/p/mtasa-resources/

And more complicated context:

- All modules use the publicsdk, which has the following (seemingly non-standard) license: https://github.com/multitheftauto/mtasa-blue/blob/master/Shared/publicsdk/LICENSE
- [~~Since all modules link in with MTA, which is GPL licensed, surely all modules are bound by the GPL?~~](https://github.com/multitheftauto/amx/issues/8#issuecomment-640229813)

Tricky!

**Comment by theSpool** [comment]
> * All modules use the publicsdk, which has the following (seemingly non-standard) license: https://github.com/multitheftauto/mtasa-blue/blob/master/Shared/publicsdk/LICENSE

Apparently this is also the [zlib/libpng](https://directory.fsf.org/wiki/License:Zlib) license, so [it should be compatible](https://www.gnu.org/licenses/license-list.en.html#ZLib) as well.

>   * https://github.com/multitheftauto/mtasa-resources is missing a license
>
>   * but I believe that repo is licensed MIT, because the old Google Code repository says it is licensed MIT: https://code.google.com/archive/p/mtasa-resources/

Then I think it's a safe assumption that `mta-resources` is licensed as MIT. That said, the [both](https://www.gnu.org/licenses/license-list.en.html#X11License) [licenses](https://www.gnu.org/licenses/license-list.en.html#Expat) that are known as "MIT License" are compatible with GPL.

> - Since all modules link in with MTA, which is GPL licensed, surely all modules are bound by the GPL?

Well then, I guess that alone settles it. The repo (this one at least) should be then licensed as GPL 3.0

**Comment by sbx320** [comment]
Another bonus: The old modules project referenced the GPL in Google Code, but the repo then continued to have LICENSE files referring to MIT/zlib licenses for the individual modules. However amx wasn't included in that repository. I'm not quite sure where the old amx module code was located. 

> Since all modules link in with MTA, which is GPL licensed, surely all modules are bound by the GPL?

No. Modules are derivatives of the publicsdk (zlib license). The modules do not link to MTA itself and are hence not convered by the GPL. 

> As a side note, I realized SA-MP violates GPL because it doesn't publicly provide the source of this file!

That's assuming the file was originally GPL licensed. For example, something that's MIT licensed can be relicensed under GPL later on, without affecting old copies.

**Comment by qaisjp** [comment]
Reading very carefully, here's the difference between the publicsdk license and the zlib license. 

Specifically the phrase "including commercial applications" vs. "excluding commercial applications"...

https://gist.github.com/qaisjp/84d97501642f95d0d70ef9f6669a1256/revisions?short_path=53e892b#diff-53e892b8b41cc4caece1cfd5ef21d6e7

**Comment by theSpool** [comment]
Boy...

What now then? To be honest I don't feel very comfortable working without a License. The publicsdk is inside the mtasa repository which is GPL 3. The [Sockets](https://wiki.multitheftauto.com/wiki/Modules/Sockets) module seems to be under GPL 3, and the MySQL Module (although old) includes MySQL Community Edition source which [also seems to be GPL](https://github.com/multitheftauto/mtasa-modules/blob/c30eb3bee7ee647a9e6d56ea9c3e0da6616f3433/mta-mysql/include/mysql/mysql_version.h#L20). These are first party modules made by MTA.

This is a time wasting mess... we're just better off assuming the publicsdk is GPL 3 as well, just like these first party modules did...

**Comment by qaisjp** [comment]
I mean I think it's safe to assume the license is this https://www.github.com/multitheftauto/mtasa-blue/tree/master/Shared%2Fpublicsdk%2FLICENSE since that's the actual original source.

(The publicsdk folder being in a repo surrounded by GPL doesn't matter because the publicsdk folder has its own license)
